# -*- mode: python -*-

Import("env")

env = env.Clone()

env.Append(CCFLAGS=['-I.'])
env.Append(CCFLAGS=['-Isrc/third_party/gflags-2.0/src'])

env.Library(
    "coding",
    [
	"coder.cc",
	"varint.cc",
    ])
